:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:sectnums:
:experimental: true

== JPA Soft Delete (Hibernate 6.4)

[IMPORTANT]
--
`@SoftDelete` 어노테이션은 Hibernate 6.4 부터 지원하는 신규 어노테이션이다.
--

이전 버전에서는 `@Where` 어노테이션을 포함한 event-listener, filter 등을 사용하여 soft delete 를 구현했다.

- Spring boot 는 3.2.1 버전부터 Hibernate 6.4 를 사용한다.

=== 참고 자료

- link:https://docs.jboss.org/hibernate/orm/6.4/migration-guide/migration-guide.html#soft-delete[Hibernate: 6.4 Migration Guide Soft Delete]
- link:https://docs.jboss.org/hibernate/orm/6.4/userguide/html_single/Hibernate_User_Guide.html#soft-delete[Hibernate: User Guide Soft Delete]
- link:https://www.baeldung.com/spring-jpa-soft-delete[Baeldung: How to Implement a Soft Delete with Spring JPA]

=== Hibernate 6.4 이전의 Soft Delete

`@SQLDelete` 어노테이션을 사용하여 delete 쿼리를 오버라이딩 하고, `@Where` 어노테이션을 사용하여 select 쿼리에 deleted=false 조건을 추가한다.

.@Where, @SQLDelete 어노테이션 사용
====
[source,java]
----
@Entity
@Table(name = "users")
@SQLDelete(sql = "UPDATE users SET deleted = true WHERE id=?")
@Where(clause = "deleted=false")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private boolean deleted = Boolean.FALSE;
    // ...
}
----
====

=== Hibernate 6.4 Soft Delete

Hibernate 6.4 부터는 `@SoftDelete` 어노테이션을 사용하여 soft delete 를 구현할 수 있다.

`@SoftDelete` 어노테이션을 사용하면 `@SQLDelete` 어노테이션을 사용하지 않아도 된다.

Soft delete 는 3가지 기능을 지원한다 -

. strategy(전략)
. column(컬럼명)
. conversion(컨버터)

==== Strategy(전략) - SoftDeleteType

Soft delete 를 사용하면 DB 에 저장하는 값을 2가지 방법으로 해석 할 수 있다.
이는 SoftDeleteType enum 으로 `@SoftDelete(..., strategy=ACTIVE)` 또는 `@SoftDelete(..., strategy=DELETED)` 지정 한다 -

====
[unordered.stack]
ACTIVE:: active 상태의 데이터를 추적한다.
`true` 값은 active (non-deleted) 상태를 의미하고, `false` 값은 inactive (deleted) 상태를 의미한다.
DELETED:: deleted 상태의 데이터를 추적한다.
`true` 값은 deleted 상태를 의미하고, `false` 값은 non-deleted 상태를 의미한다.
====

==== Column(컬럼명) - Indicator column

`@SoftDelete#columnName` 속성을 사용하여 soft delete 를 저장할 컬럼명을 지정한다.

기본 컬럼명은 사용하는 전략(SoftDeleteType) 에 따라 저장된다 -

====
[unordered.stack]
ACTIVE:: 기본 컬럼명은 `active` 이다.
DELETED:: 기본 컬럼명은 `deleted` 이다.
====

==== Conversion(컨버터) - Converter

값의 변환은 Jakarta Persistence AttributeConverter 를 사용하여 수행한다. domain-type 은 boolean 이고, relational-type 은 컨버터에 저의된 값을 따라간다; 일반적으로는 `BOOLEAN`, `INTEGER` 또는 `CHAR` 이다.

예를 들어, `YesNoConverter` 를 사용하면 `Y` 또는 `N` 값을 사용한다.

`@SoftDelete#converter` 속성을 사용하여 컨버터를 지정한다.
만약 converter 속성을 사용하지 않으면, Hibernate 가 DB 에 따라 컨버터를 자동으로 선택된다.

==== Entity soft delete 예제

.@SoftDelete 어노테이션 사용
====
[source,java]
----
@Entity
@Table(name = "users")
@SoftDelete(columnName = "deleted", strategy = SoftDeleteType.DELETED, converter = YesNoConverter.class)
public class User {
    // ...
}
----
====

