spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
            loggerLevel: headers
            default-request-headers:
              User-Agent: http-client-of
              Content-Type: application/json
              Accept: application/json