spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 500
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 500
        query:
          mutation_strategy: org.hibernate.query.sqm.mutation.internal.inline.InlineMutationStrategy
    open-in-view: false

---
# =====================================================================================================================
# local
# =====================================================================================================================
spring:
  config:
    activate:
      on-profile: local
  # ==============================
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      pool-name: pips-local-DS
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 300000
      minimum-idle: 2
      maximum-pool-size: 10
  # ==============================
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        format_sql: true
    generate-ddl: true
    show-sql: true
    open-in-view: false

---




