spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 500
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 500
        query:
          mutation_strategy: org.hibernate.query.sqm.mutation.internal.inline.InlineMutationStrategy
    open-in-view: false


---
# =====================================================================================================================
# local
# =====================================================================================================================
spring:
  config:
    activate:
      on-profile: local
  # ==============================
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    #    url: jdbc:oracle:thin:@localhost:1521:XE
    #    username: smilecon
    #    password: 1234
    #    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      pool-name: smilecon-local-DS
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 300000
      minimum-idle: 2
      maximum-pool-size: 3
  # ==============================
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    generate-ddl: true

# =====================================================================================================================
# logging
# =====================================================================================================================
logging:
  group:
    app: "io.glory"
    hikari: "com.zaxxer.hikari"
    transaction: "org.springframework.transaction, org.springframework.orm.jpa.JpaTransactionManager, org.hibernate.engine.transaction.internal.TransactionImpl"
    query: "org.hibernate.SQL, org.hibernate.SQL_SLOW"
    bind: "org.hibernate.orm.jdbc.bind"
  level:
    app: debug
    sql: debug
    query: debug
    bind: trace

---




